var pb_data =[{'name': 'South Asia',
  'data': [{'name': 'Afghanistan', 'value': 64.83},
   {'name': 'Bangladesh', 'value': 72.59},
   {'name': 'Bhutan', 'value': 71.78},
   {'name': 'India', 'value': 69.66},
   {'name': 'Maldives', 'value': 78.92},
   {'name': 'Nepal', 'value': 70.78},
   {'name': 'Pakistan', 'value': 67.27},
   {'name': 'Sri Lanka', 'value': 76.98}]},
 {'name': 'Europe & Central Asia',
  'data': [{'name': 'Albania', 'value': 78.57},
   {'name': 'Armenia', 'value': 75.09},
   {'name': 'Austria', 'value': 81.79},
   {'name': 'Azerbaijan', 'value': 73.0},
   {'name': 'Belarus', 'value': 74.23},
   {'name': 'Belgium', 'value': 81.75},
   {'name': 'Bosnia and Herzegovina', 'value': 77.4},
   {'name': 'Bulgaria', 'value': 74.91},
   {'name': 'Channel Islands', 'value': 83.09},
   {'name': 'Croatia', 'value': 78.42},
   {'name': 'Cyprus', 'value': 80.98},
   {'name': 'Czech Republic', 'value': 79.13},
   {'name': 'Denmark', 'value': 81.2},
   {'name': 'Estonia', 'value': 78.5},
   {'name': 'Finland', 'value': 81.79},
   {'name': 'France', 'value': 82.58},
   {'name': 'Georgia', 'value': 73.77},
   {'name': 'Germany', 'value': 80.94},
   {'name': 'Greece', 'value': 81.94},
   {'name': 'Hungary', 'value': 76.02},
   {'name': 'Iceland', 'value': 82.56},
   {'name': 'Ireland', 'value': 82.3},
   {'name': 'Italy', 'value': 83.2},
   {'name': 'Kazakhstan', 'value': 73.18},
   {'name': 'Kyrgyz Republic', 'value': 71.6},
   {'name': 'Latvia', 'value': 75.24},
   {'name': 'Lithuania', 'value': 76.13},
   {'name': 'Luxembourg', 'value': 82.45},
   {'name': 'Moldova', 'value': 71.9},
   {'name': 'Montenegro', 'value': 76.88},
   {'name': 'Netherlands', 'value': 82.01},
   {'name': 'North Macedonia', 'value': 75.8},
   {'name': 'Norway', 'value': 82.91},
   {'name': 'Poland', 'value': 77.86},
   {'name': 'Portugal', 'value': 80.68},
   {'name': 'Romania', 'value': 75.46},
   {'name': 'Russian Federation', 'value': 73.08},
   {'name': 'Serbia', 'value': 75.69},
   {'name': 'Slovak Republic', 'value': 77.47},
   {'name': 'Slovenia', 'value': 81.28},
   {'name': 'Spain', 'value': 83.49},
   {'name': 'Sweden', 'value': 82.96},
   {'name': 'Switzerland', 'value': 83.7},
   {'name': 'Tajikistan', 'value': 71.1},
   {'name': 'Turkey', 'value': 77.69},
   {'name': 'Turkmenistan', 'value': 68.19},
   {'name': 'Ukraine', 'value': 71.83},
   {'name': 'United Kingdom', 'value': 81.2},
   {'name': 'Uzbekistan', 'value': 71.72}]},
 {'name': 'Middle East & North Africa',
  'data': [{'name': 'Algeria', 'value': 76.88},
   {'name': 'Bahrain', 'value': 77.29},
   {'name': 'Djibouti', 'value': 67.11},
   {'name': 'Iraq', 'value': 70.6},
   {'name': 'Israel', 'value': 82.8},
   {'name': 'Jordan', 'value': 74.53},
   {'name': 'Kuwait', 'value': 75.49},
   {'name': 'Lebanon', 'value': 78.93},
   {'name': 'Libya', 'value': 72.91},
   {'name': 'Malta', 'value': 82.6},
   {'name': 'Morocco', 'value': 76.68},
   {'name': 'Oman', 'value': 77.86},
   {'name': 'Qatar', 'value': 80.23},
   {'name': 'Saudi Arabia', 'value': 75.13},
   {'name': 'Syrian Arab Republic', 'value': 72.7},
   {'name': 'Tunisia', 'value': 76.7},
   {'name': 'United Arab Emirates', 'value': 77.97}]},
 {'name': 'East Asia & Pacific',
  'data': [{'name': 'Australia', 'value': 82.9},
   {'name': 'Brunei Darussalam', 'value': 75.86},
   {'name': 'Cambodia', 'value': 69.82},
   {'name': 'China', 'value': 76.91},
   {'name': 'Fiji', 'value': 67.44},
   {'name': 'Indonesia', 'value': 71.72},
   {'name': 'Japan', 'value': 84.36},
   {'name': 'Kiribati', 'value': 68.37},
   {'name': 'Lao PDR', 'value': 67.92},
   {'name': 'Malaysia', 'value': 76.16},
   {'name': 'Mongolia', 'value': 69.87},
   {'name': 'Myanmar', 'value': 67.13},
   {'name': 'New Zealand', 'value': 81.71},
   {'name': 'Papua New Guinea', 'value': 64.5},
   {'name': 'Philippines', 'value': 71.23},
   {'name': 'Samoa', 'value': 73.32},
   {'name': 'Singapore', 'value': 83.5},
   {'name': 'Solomon Islands', 'value': 73.0},
   {'name': 'Thailand', 'value': 77.15},
   {'name': 'Timor-Leste', 'value': 69.5},
   {'name': 'Tonga', 'value': 70.91},
   {'name': 'Vanuatu', 'value': 70.47},
   {'name': 'Vietnam', 'value': 75.4}]},
 {'name': 'Sub-Saharan Africa',
  'data': [{'name': 'Angola', 'value': 61.15},
   {'name': 'Benin', 'value': 61.77},
   {'name': 'Botswana', 'value': 69.59},
   {'name': 'Burkina Faso', 'value': 61.58},
   {'name': 'Burundi', 'value': 61.58},
   {'name': 'Cabo Verde', 'value': 72.98},
   {'name': 'Cameroon', 'value': 59.29},
   {'name': 'Central African Republic', 'value': 53.28},
   {'name': 'Chad', 'value': 54.24},
   {'name': 'Comoros', 'value': 64.32},
   {'name': 'Equatorial Guinea', 'value': 58.73},
   {'name': 'Eritrea', 'value': 66.32},
   {'name': 'Eswatini', 'value': 60.19},
   {'name': 'Ethiopia', 'value': 66.6},
   {'name': 'Gabon', 'value': 66.47},
   {'name': 'Ghana', 'value': 64.07},
   {'name': 'Guinea', 'value': 61.6},
   {'name': 'Guinea-Bissau', 'value': 58.32},
   {'name': 'Kenya', 'value': 66.7},
   {'name': 'Lesotho', 'value': 54.33},
   {'name': 'Liberia', 'value': 64.1},
   {'name': 'Madagascar', 'value': 67.04},
   {'name': 'Malawi', 'value': 64.26},
   {'name': 'Mali', 'value': 59.31},
   {'name': 'Mauritania', 'value': 64.92},
   {'name': 'Mauritius', 'value': 74.24},
   {'name': 'Mozambique', 'value': 60.85},
   {'name': 'Namibia', 'value': 63.71},
   {'name': 'Niger', 'value': 62.42},
   {'name': 'Nigeria', 'value': 54.69},
   {'name': 'Rwanda', 'value': 69.02},
   {'name': 'Senegal', 'value': 67.94},
   {'name': 'Seychelles', 'value': 73.94},
   {'name': 'Sierra Leone', 'value': 54.7},
   {'name': 'Somalia', 'value': 57.4},
   {'name': 'South Africa', 'value': 64.13},
   {'name': 'South Sudan', 'value': 57.85},
   {'name': 'Sudan', 'value': 65.31},
   {'name': 'Tanzania', 'value': 65.46},
   {'name': 'Togo', 'value': 61.04},
   {'name': 'Uganda', 'value': 63.37},
   {'name': 'Zambia', 'value': 63.89},
   {'name': 'Zimbabwe', 'value': 61.49}]},
 {'name': 'Latin America & Caribbean',
  'data': [{'name': 'Antigua and Barbuda', 'value': 77.02},
   {'name': 'Argentina', 'value': 76.67},
   {'name': 'Barbados', 'value': 79.19},
   {'name': 'Belize', 'value': 74.62},
   {'name': 'Bolivia', 'value': 71.51},
   {'name': 'Brazil', 'value': 75.88},
   {'name': 'Chile', 'value': 80.18},
   {'name': 'Colombia', 'value': 77.29},
   {'name': 'Costa Rica', 'value': 80.28},
   {'name': 'Cuba', 'value': 78.8},
   {'name': 'Dominican Republic', 'value': 74.08},
   {'name': 'Ecuador', 'value': 77.01},
   {'name': 'El Salvador', 'value': 73.32},
   {'name': 'Grenada', 'value': 72.4},
   {'name': 'Guatemala', 'value': 74.3},
   {'name': 'Guyana', 'value': 69.91},
   {'name': 'Haiti', 'value': 64.0},
   {'name': 'Honduras', 'value': 75.27},
   {'name': 'Jamaica', 'value': 74.47},
   {'name': 'Mexico', 'value': 75.05},
   {'name': 'Nicaragua', 'value': 74.48},
   {'name': 'Panama', 'value': 78.51},
   {'name': 'Paraguay', 'value': 74.25},
   {'name': 'Peru', 'value': 76.74},
   {'name': 'St. Lucia', 'value': 76.2},
   {'name': 'St. Vincent and the Grenadines', 'value': 72.53},
   {'name': 'Suriname', 'value': 71.68},
   {'name': 'Trinidad and Tobago', 'value': 73.51},
   {'name': 'Uruguay', 'value': 77.91}]},
 {'name': 'North America',
  'data': [{'name': 'Canada', 'value': 82.05},
   {'name': 'United States', 'value': 78.79}]},
];

   Highcharts.chart('pb-container', {
    chart: {
        type: 'packedbubble',
        height: '60%'
    },
    title: {
        text: 'Life Expectancy Around the World (Region Wise)'
    },
    tooltip: {
        useHTML: true,
        pointFormat: '<b>{point.name}:</b> {point.value} Years</sub>'
    },
    plotOptions: {
        packedbubble: {
            minSize: '-2%',
            maxSize: '150%',
            zMin: 0,
            zMax: 500,
            layoutAlgorithm: {
                gravitationalConstant: 0.05,
                splitSeries: true,
                seriesInteraction: false,
                dragBetweenSeries: true,
                parentNodeLimit: true
            },
            dataLabels: {
                enabled: true,
                format: '{point.name}',
                filter: {
                    property: 'y',
                    operator: '>',
                    value: 80
                },
                style: {
                    color: 'black',
                    textOutline: 'none',
                    fontWeight: 'normal'
                }
            }
        }
    },
    series: pb_data,
})

